# Generated by Django 6.1.1 on 2026-09-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+91 98765 43210', help_text='Primary contact phone number', max_length=50)),
                ('phone_hours', models.CharField(default='Mon – Sat: 8:00 AM – 8:00 PM', help_text='Operating hours for phone support', max_length=100)),
                ('email_address', models.EmailField(default='hello@sproutsbox.in', help_text='Primary contact email address', max_length=254)),
                ('email_note', models.CharField(default='Support & General Inquiries', help_text='Subtext under email address', max_length=100)),
                ('address_line1', models.CharField(default='Sprouts Box Eco Farm, Green Valley', help_text='Address Line 1', max_length=255)),
                ('address_line2', models.CharField(default='Kerala, India – 682001', help_text='Address Line 2', max_length=255)),
                ('contact_subtitle', models.CharField(default='Reach Out —', help_text='Subtitle above Contact Information header', max_length=200)),
                ('contact_title', models.CharField(default='Contact Information', help_text='Main heading on Contact Information column', max_length=200)),
                ('contact_intro', models.TextField(default="Whether you're looking for home delivery or want to partner with us, our team is ready to assist you.", help_text='Description paragraph under Contact Information heading')),
                ('instagram_url', models.CharField(blank=True, default='#', help_text='Instagram profile or page link', max_length=500)),
                ('facebook_url', models.CharField(blank=True, default='#', help_text='Facebook profile or page link', max_length=500)),
                ('youtube_url', models.CharField(blank=True, default='#', help_text='YouTube channel link', max_length=500)),
                ('whatsapp_url', models.CharField(blank=True, default='#', help_text='WhatsApp contact/group link', max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
